### ISSUE TITLE
Logo Proposal for HabitJournal

### ISSUE THREAD

**Issue by leonardoderoy** [jayantadn/HabitChart#35]
Hello! @jayantadn

I'm a graphic designer and I like to support open source projects. I would like to design a logo for your project if you interested, I will be happy to work with you! :)

Best Regards
Leonardo Deroy 

Graphic Designer

**Comment by jayantadn** [comment]
yes, I am very much interested. I need an icon for my app. I am very close to making my first official release on Android.
My app is basically a habit tracking app. User adds a habit like "reduce cigarettes" and adds consumption data everyday. The app will show the progress chart and a status sign. That way the user tracks whether the target is being achieved or not.
My current icon is this:
![logo](https://user-images.githubusercontent.com/32790085/42126288-10d4f9ca-7c86-11e8-9102-32efc35f0756.png)
I would be very happy to have an icon ideated by a designer.

If you want more details, please comment back.

**Comment by leonardoderoy** [comment]
Hi @jayantadn  The exact name would be very useful

**Comment by jayantadn** [comment]
Habit Journal

**Comment by jayantadn** [comment]
@leonardoderoy any update?

**Comment by leonardoderoy** [comment]
hellow @jayantadn  I'm about to upload the proposal

**Comment by leonardoderoy** [comment]
Hello, this can do anything you want
![image](https://user-images.githubusercontent.com/40496274/42244434-03a865de-7ee3-11e8-94f0-80360c1632a6.png)

**Comment by jayantadn** [comment]
Thanks a lot. They look really awesome. I am inclined towards the first column. Give me some time, I will confirm you.

**Comment by leonardoderoy** [comment]
ok no problem, let me know to do the pull requests with the proposal you choose

**Comment by jayantadn** [comment]
@leonardoderoy Will it be possible to make 5 with blue color theme as in 10? Although i am not sure if you have to keep the remaining colors of 5 the same, or probably you have to change those to have a good contrast. Please give it a try, lets see how it turns out.

**Comment by jayantadn** [comment]
@leonardoderoy I was planning to publish my app to google play store coming weekend. Do you think you can have the logo ready by then?

**Comment by jayantadn** [comment]
Hi again, I took the liberty to draft the logo myself a bit :)
![logo](https://user-images.githubusercontent.com/32790085/42505263-8ea4f78c-843e-11e8-879d-5dc26ee3be25.png)

**Comment by jayantadn** [comment]
closing the issue because no response from @leonardoderoy
